apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-application
  template:
    metadata:
      labels:
        app: k8s-application
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.containerPort }}
