apiVersion: v1
kind: Service
metadata:
  name: k8s-application-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: k8s-application
